### ISSUE TITLE
[FEAT] need a JS date converter function

### ISSUE THREAD

**Issue by lego651** [lego651/social-pomo#13]
需要一个JS util function, convert 年/月/日 => 一个数
function (year, month, day) => number 

具体要求:
我们把2020/1/1号定为0, 2020/1/2就是1，2020/1/3就是2... 依次往上加。
于是乎: 2020/1/31应该返回30, 2020/2/1应该返回31, 2020/12/31应该返回365(2020年是闰年，一共366天，需要考虑和判断闰年情况); 
需要考虑2020年到2120年; 2021/1/1 应该返回366...etc...

请在src/utils/util.js 里面创建一个 convertDate(year,month,date){ ... } function

**Comment by cathy651** [comment]
public class daysBetweenDates {
	public static void main(String[] args){
		int y1 = 2019;
		int y2 = 2021;
		int m1 = 1;
		int m2 = 1;
		int d1 = 3; 
		int d2 = 3;
		
		int y;
		int count = 0;
		for(y = y1; y < y2; y++){
			if(y % 4 == 0 && (y % 100 != 0 || y % 400 == 0)){
				count++;
			}
		}
		int days1=intdateOfCurYear(y1,m1,d1);
		int days2=intdateOfCurYear(y2,m2,d2);
	    int finalRes = (y2-y1)*365 + count + days2 - days1;
	    System.out.println(finalRes);
	}
	public static int intdateOfCurYear(int y,int m,int d){
		int[] months = {31, 28, 31, 30, 31, 30 , 31 , 31, 30, 31, 30 ,31};
	    int res = 0;
	    for(int i =0; i< m -1;i++) res += months[i];    
	    return res + d + (m > 2 && y % 4 == 0 && (y % 100 != 0 || y % 400 == 0) ? 1 : 0);
	}
}

**Comment by cathy651** [comment]
这个是我JAVA 的code, 但是JS 的code 暂时有问题，我再看看

**Comment by lego651** [comment]
`

function convertDateToSeq(y, m, d) {
	const startYear = 2020;
  const months = [31, 28, 31, 30, 31, 30 , 31 , 31, 30, 31, 30 ,31];
  let res = 0;
  
 	let year = startYear;
  let month = 0; 
  while (year < y) {
  	res += year % 4 === 0 ? 366 : 365;
    year++;
  }
  
  while(month < m) {
  	if(y % 4 === 0 && month === 1) {
    	res += months[month] + 1;
    } else {
    	res += months[month];
    }
  	month++;
  }
  
  return res + d;
}

console.log(convertDateToSeq(2020, 0, 1));
console.log(convertDateToSeq(2020, 1, 29)); // 29 + 31 = 60
console.log(convertDateToSeq(2020, 2, 1));
console.log(convertDateToSeq(2020, 11, 31));
console.log(convertDateToSeq(2021, 0, 1));



`

**Comment by lego651** [comment]
``` javascript


function convertDateToSeq(y, m, d) {
	const startYear = 2020;
  const months = [31, 28, 31, 30, 31, 30 , 31 , 31, 30, 31, 30 ,31];
  let res = 0;
  
 	let year = startYear;
  let month = 0; 
  while (year < y) {
  	res += year % 4 === 0 ? 366 : 365;
    year++;
  }
  
  while(month < m) {
  	if(y % 4 === 0 && month === 1) {
    	res += months[month] + 1;
    } else {
    	res += months[month];
    }
  	month++;
  }
  
  return res + d;
}

console.log(convertDateToSeq(2020, 0, 1));
console.log(convertDateToSeq(2020, 1, 29)); // 29 + 31 = 60
console.log(convertDateToSeq(2020, 2, 1));
console.log(convertDateToSeq(2020, 11, 31));
console.log(convertDateToSeq(2021, 0, 1));




```

**Comment by lego651** [comment]
``` javascript


function convertDateToSeq(y, m, d) {
	const startYear = 2020;
  const months = [31, 28, 31, 30, 31, 30 , 31 , 31, 30, 31, 30 ,31];
  let res = 0;
  
 	let year = startYear;
  let month = 0; 
  while (year < y) {
  	res += year % 4 === 0 ? 366 : 365;
    year++;
  }
  
  while(month < m - 1) {
  	if(y % 4 === 0 && month === 1) {
    	res += months[month] + 1;
    } else {
    	res += months[month];
    }
  	month++;
  }
  
  return res + d;
}

console.log(convertDateToSeq(2020, 1, 1));
console.log(convertDateToSeq(2020, 2, 29)); // 29 + 31 = 60
console.log(convertDateToSeq(2020, 3, 1));
console.log(convertDateToSeq(2020, 12, 31));
console.log(convertDateToSeq(2021, 1, 1)); 




```

**Comment by cathy651** [comment]
```javascript
function convertDateToSeq(y, m, d) {
	const days2020 = new Date(2020,1-1,1);
  let days = new  Date(y,m-1,d);
  let res = 0;
  res =  (days-days2020)/(24*60*60*1000);
  return res;
}

console.log(convertDateToSeq(2020, 1, 29)); // 29 + 31 = 60
console.log(convertDateToSeq(2020, 2, 1));
console.log(convertDateToSeq(2020, 11, 31));
console.log(convertDateToSeq(2021, 0, 1));
```
