### ISSUE TITLE
[FIX]meeting room nick name

### ISSUE THREAD

**Issue by cathy651** [lego651/social-pomo#22]
<img width="749" alt="Screen Shot 2020-03-22 at 9 07 34 PM" src="https://user-images.githubusercontent.com/19277796/77280375-5de39b80-6c81-11ea-96ea-18c5e0b70551.png">
头像和用户名都没有更新

**Comment by cathy651** [comment]
头像和用户名都没有更新

**Comment by JasonGao99** [comment]
![image](https://user-images.githubusercontent.com/11490316/77280558-e82bff80-6c81-11ea-9d74-a7dbab723512.png)
