### ISSUE TITLE
[FIX] interesting room name 

### ISSUE THREAD

**Issue by cathy651** [lego651/social-pomo#8]
1. 随便输入一个不存在的roomname 例如c4 点击join room. 你会发现进不去，这是正常的

2. 点击match, 就算没有match 到也直接返回首页。然后你会发现你刚才输入的c4 存在了，可以直接join,但是又不在你的room 列表里
<img width="702" alt="Screen Shot 2020-01-31 at 11 23 45 PM" src="https://user-images.githubusercontent.com/19277796/73588720-6ab5f100-4481-11ea-9f06-7f7e4670bcb9.png">

**Comment by JasonGao99** [comment]
Resolved. Please verify, then close this issue if confirmed. @cathy651

**Comment by cathy651** [comment]
LGTM. Jason fixed on 03/16/2020.
